[package]
name = "rusthour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
num-traits = "0.2.15"
bench = "1.1.0"